apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jb25uZWN0LnJlZGhhdC5jb20iOnsidXNlcm5hbWUiOiJqcGVyZXouaGRzIiwicGFzc3dvcmQiOiJIaXRhY2hpMSEiLCJhdXRoIjoiYW5CbGNtVjZMbWhrY3pwSWFYUmhZMmhwTVNFPSJ9fX0=
kind: Secret
metadata:
  name: regcred-redhat-com
  namespace: hspc-operator-system
type: kubernetes.io/dockerconfigjson